# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FINANCIER(object):
    def setupUi(self, FINANCIER):
        FINANCIER.setObjectName("FINANCIER")
        FINANCIER.resize(734, 550)
        FINANCIER.setStyleSheet("background-color: #EC933B    ")
        self.label = QtWidgets.QLabel(FINANCIER)
        self.label.setGeometry(QtCore.QRect(260, 30, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FFFFFF")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(FINANCIER)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 470, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: #FFFFFF;\n"
"color: #5C2E00")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(FINANCIER)
        self.textEdit.setGeometry(QtCore.QRect(80, 130, 601, 281))
        self.textEdit.setStyleSheet("color: #5C2E00;\n"
"background-color: #ffffff")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(FINANCIER)
        QtCore.QMetaObject.connectSlotsByName(FINANCIER)

    def retranslateUi(self, FINANCIER):
        _translate = QtCore.QCoreApplication.translate
        FINANCIER.setWindowTitle(_translate("FINANCIER", "Financier"))
        self.label.setText(_translate("FINANCIER", "Инструкция"))
        self.pushButton_2.setText(_translate("FINANCIER", "Дальше"))
        self.textEdit.setHtml(_translate("FINANCIER", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Данное финансовое приложение создано для контроля ваших расходов. После нажания кнопки &quot;Дальше&quot; - откроется главный экран. На нем вы увидете переход в &quot;Настройки&quot; приложения, &quot;Траты&quot; и страницу &quot;Отчет&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">В первом окне вы можете добавить необходимые сферы расходов, а также удалить их или ошибочно введенные данные.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">В окне &quot;Траты&quot; необходимо выбрать сферу расходов, сумму и дату платежа.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Для просмотра графика расходов и анализа расходов перейдите во вкладку &quot;Отчет&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Также вы можете посмотреть данное руководство еще раз при переходе во вкладку &quot;Инструкция&quot;. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Для закрытия приложения пользуйтесь соответствующей кнопкой.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FINANCIER = QtWidgets.QWidget()
    ui = Ui_FINANCIER()
    ui.setupUi(FINANCIER)
    FINANCIER.show()
    sys.exit(app.exec_())
