# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vxod.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization(object):
    def setupUi(self, authorization):
        authorization.setObjectName("authorization")
        authorization.resize(699, 363)
        authorization.setStyleSheet("background-color: #EC933B    ")
        self.label = QtWidgets.QLabel(authorization)
        self.label.setGeometry(QtCore.QRect(270, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #8D4600")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(authorization)
        self.label_2.setGeometry(QtCore.QRect(360, 90, 361, 261))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("money.png"))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(authorization)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 90, 291, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setStyleSheet("background-color: #FFFFFF")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setStyleSheet("background-color: #FFFFFF")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #FFFFFF;\n"
"color: #5C2E00")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: #FFFFFF;\n"
"color: #5C2E00")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(authorization)
        QtCore.QMetaObject.connectSlotsByName(authorization)

    def retranslateUi(self, authorization):
        _translate = QtCore.QCoreApplication.translate
        authorization.setWindowTitle(_translate("authorization", "Financier"))
        self.label.setText(_translate("authorization", "FINANCIER"))
        self.lineEdit_2.setPlaceholderText(_translate("authorization", "Login"))
        self.lineEdit.setPlaceholderText(_translate("authorization", "Password"))
        self.pushButton.setText(_translate("authorization", "Войти"))
        self.pushButton_2.setText(_translate("authorization", "Зарегестрироваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authorization = QtWidgets.QWidget()
    ui = Ui_authorization()
    ui.setupUi(authorization)
    authorization.show()
    sys.exit(app.exec_())
